name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: self-hosted
    env:
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_ACCOUNT_KEY:  ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker run -v /var/run/docker.sock:/var/run/docker.sock  build -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v major
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-west2-docker.pkg.dev --quiet
    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker run -v /var/run/docker.sock:/var/run/docker.sock  tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker run -v /var/run/docker.sock:/var/run/docker.sock  tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker run -v /var/run/docker.sock:/var/run/docker.sock  push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker run -v /var/run/docker.sock:/var/run/docker.sock  push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker run -v /var/run/docker.sock:/var/run/docker.sock  tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker run -v /var/run/docker.sock:/var/run/docker.sock  tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker run -v /var/run/docker.sock:/var/run/docker.sock  push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker run -v /var/run/docker.sock:/var/run/docker.sock  push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
